kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata
handler: kata
overhead:
    podFixed:
        memory: "160Mi"
        cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache-kata-qemu
  labels:
    app: php-apache-kata-qemu
spec:
  replicas: 1
  selector:
    matchLabels:
      run: php-apache-kata-qemu
  template:
    metadata:
      annotations:
        io.katacontainers.config.runtime.disable_guest_seccomp: "false"
      labels:
        run: php-apache-kata-qemu
    spec:
      runtimeClassName: kata
      containers:
      - image: headers:latest
        name: headers
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /run/current-system/
          name: current-system
        - mountPath: /tmp/
          name: tmp
      volumes:
      - name: current-system
        hostPath:
          path: /run/current-system/
      - name: tmp
        hostPath:
          path: /tmp/
