{ config, pkgs, pkgs-unstable, lib, ... }:

{
  programs.aerc = {
    package = pkgs-unstable.aerc;
    enable = true;
    extraConfig = {
      general.unsafe-accounts-conf = true;
      general.disable-ipc = false;

      filters = {
        "text/plain" = "colorize";
        "text/markdown" = "mdcat";
        "text/html" = "! html";
      };

      ui = {
        styleset-name = "current";
        border-char-vertical = "│";
        border-char-horizontal = "─";
      };
    };
  };


  home.packages = with pkgs; [
    mdcat
    aba
  ];

  home.sessionVariables = {
    # workaround for https://github.com/NixOS/nixpkgs/issues/195532
    EMAIL_CONN_TEST = "n";
  };


  accounts.email = {
    maildirBasePath = "mail";
    accounts = {
      "me@flakm.com" = {
        realName = "Maciek Flak";
        aerc = {
          enable = true;
          extraAccounts = {
            check-mail = "5m";
            check-mail-cmd = "mbsync -a";
            check-mail-timeout = "2m";
            address-book-cmd = "aba -a ${config.home.homeDirectory}/.config/aba.toml ls \"%s\"";
          };
        };
        primary = true;
        address = "me@flakm.com";
        flavor = "fastmail.com";
        signature = {
          showSignature = "append";
          text = ''
            Regards,
            Maciek Flak
          '';
        };
        imap = {
          host = "imap.fastmail.com";
          tls.enable = true;
        };
        smtp = {
          host = "smtp.fastmail.com";
          port = 587;
          tls.enable = true;
          tls.useStartTls = true;
        };
        mbsync = {
          enable = true;
          create = "both";
          expunge = "both";
        };
        msmtp = {
          enable = true;
          extraConfig = {
            from = "me@flakm.com";
          };
        };
        passwordCommand = "cat ${config.home.homeDirectory}/.neomutt_flakm";
        imapnotify = {
          enable = true;
        };
      };


      "maciej.jan.flak@gmail.com" = {
        realName = "Maciej Jan Flak";
        aerc = {
          enable = true;
          extraAccounts = {
            # XDG_DATA_HOME
            address-book-cmd = "aba -a ${config.home.homeDirectory}/.config/aba.toml ls \"%s\"";
          };
        };
        address = "maciej.jan.flak@gmail.com";
        flavor = "gmail.com";
        signature = {
          showSignature = "append";
          text = ''
            Best regards,
            Maciej Jan Flak
          '';
        };
        imap = {
          host = "imap.gmail.com";
          port = 993;
          tls.enable = true;
        };
        smtp = {
          host = "smtp.gmail.com";
          port = 587;
          tls.enable = true;
          tls.useStartTls = true;
        };
        mbsync = {
          enable = true;
          create = "both";
          expunge = "both";
        };
        msmtp.enable = true;
        passwordCommand = "cat ${config.home.homeDirectory}/.neomutt_gmail";
        imapnotify = {
          enable = true;
        };
      };

    };
  };



  programs = {
    mbsync.enable = true;
    msmtp.enable = true;
  };

  services.imapnotify.enable = true;



  # Write the catppuccin-mocha styleset
  home.file."Library/Preferences/aerc/stylesets/dark" = {
    text = ''
      # Generated by Home Manager.

      *.default=true
      *.normal=true

      default.fg=#cdd6f4

      error.fg=#f38ba8
      warning.fg=#fab387
      success.fg=#a6e3a1

      tab.fg=#6c7086
      tab.bg=#181825
      tab.selected.fg=#cdd6f4
      tab.selected.bg=#1e1e2e
      tab.selected.bold=true

      border.fg=#11111b
      border.bold=true

      msglist_unread.bold=true
      msglist_flagged.fg=#f9e2af
      msglist_flagged.bold=true
      msglist_result.fg=#89b4fa
      msglist_result.bold=true
      msglist_*.selected.bold=true
      msglist_*.selected.bg=#313244

      dirlist_*.selected.bold=true
      dirlist_*.selected.bg=#313244

      statusline_default.fg=#9399b2
      statusline_default.bg=#313244
      statusline_error.bold=true
      statusline_success.bold=true

      completion_default.selected.bg=#313244

      [viewer]
      url.fg=#89b4fa
      url.underline=true
      header.bold=true
      signature.dim=true
      diff_meta.bold=true
      diff_chunk.fg=#89b4fa
      diff_chunk_func.fg=#89b4fa
      diff_chunk_func.bold=true
      diff_add.fg=#a6e3a1
      diff_del.fg=#f38ba8
      quote_*.fg=#6c7086
      quote_1.fg=#9399b2
    '';
  };

  # Write the catppuccin-latte styleset
  home.file."Library/Preferences/aerc/stylesets/light" = {
    text = ''
      # Generated by Home Manager.

      *.default=true
      *.normal=true

      default.fg=#4c4f69

      error.fg=#d20f39
      warning.fg=#fe640b
      success.fg=#40a02b

      tab.fg=#9ca0b0
      tab.bg=#e6e9ef
      tab.selected.fg=#4c4f69
      tab.selected.bg=#eff1f5
      tab.selected.bold=true

      border.fg=#dce0e8
      border.bold=true

      msglist_unread.bold=true
      msglist_flagged.fg=#df8e1d
      msglist_flagged.bold=true
      msglist_result.fg=#1e66f5
      msglist_result.bold=true
      msglist_*.selected.bold=true
      msglist_*.selected.bg=#ccd0da

      dirlist_*.selected.bold=true
      dirlist_*.selected.bg=#ccd0da

      statusline_default.fg=#7c7f93
      statusline_default.bg=#ccd0da
      statusline_error.bold=true
      statusline_success.bold=true

      completion_default.selected.bg=#ccd0da

      [viewer]
      url.fg=#1e66f5
      url.underline=true
      header.bold=true
      signature.dim=true
      diff_meta.bold=true
      diff_chunk.fg=#1e66f5
      diff_chunk_func.fg=#1e66f5
      diff_chunk_func.bold=true
      diff_add.fg=#40a02b
      diff_del.fg=#d20f39
      quote_*.fg=#9ca0b0
      quote_1.fg=#7c7f93
    '';
  };

}
